// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

namespace IxMilia.Iges.Entities
{
    public enum IgesEntityType
    {
        Null = 0,
        CircularArc = 100,
        CompositeCurve = 102,
        ConicArc = 104,
        CopiousData = 106,
        Plane = 108,
        Line = 110,
        ParametricSplineCurve = 112,
        ParametricSplineSurface = 114,
        Point = 116,
        RuledSurface = 118,
        SurfaceOfRevolution = 120,
        TabulatedCylinder = 122,
        Direction = 123,
        TransformationMatrix = 124,
        Flash = 125,
        RationalBSplineCurve = 126,
        RationalBSplineSurface = 128,
        OffsetCurve = 130,
        ConnectPoint = 132,
        Node = 134,
        FiniteElement = 136,
        NodalDisplacementAndRotation = 138,
        OffsetSurface = 140,
        Boundary = 141,
        CurveOnAParametricSurface = 142,
        BoundedSurface = 143,
        TrimmedParametricSurface = 144,
        NodalResults = 146,
        ElementResults = 148,
        Block = 150,
        RightAngularWedge = 152,
        RightCircularCylinder = 154,
        RightCircularConeFrustrum = 156,
        Sphere = 158,
        Torus = 160,
        SolidOfRevolution = 162,
        SolidOfLinearExtrusion = 164,
        GeneralNote = 212,
        Leader = 214,
        LineFontDefinition = 304,
        SubfigureDefinition = 308,
        TextFontDefinition = 310,
        TextDisplayTemplate = 312,
        ColorDefinition = 314,
        AssociativityInstance = 402,
        Property = 406,
        View = 410
    }
}
